import React from 'react'
import { Button } from '@mantine/core'
import Head from 'next/head'
import axios from 'axios'
import Login from '../layout/Login'
import { PermissionContext } from '../layout/Layout'
import { UserData } from '../components'
import { ManagerStats, LogistStats, ServiceStats, PurchaseStats, AdminStats } from '../components/stats'


const Home = () => {

  const {manager, logist, service, purchase, transac, admin} = React.useContext(PermissionContext)

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> 
      <UserData/>
      <div className='mt-8'>
        {manager && <ManagerStats/>}
        {logist && <LogistStats/>}
        {service && <ServiceStats/>}
        {purchase && <PurchaseStats/>}
        {admin && <AdminStats/>}
      </div>
    
      <Login />
    </div>
  )
}

export default Home
